# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'vtnPrincipal.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QSplitter, QStatusBar, QWidget)

class Ui_vtnPrincipal(object):
    def setupUi(self, vtnPrincipal):
        if not vtnPrincipal.objectName():
            vtnPrincipal.setObjectName(u"vtnPrincipal")
        vtnPrincipal.resize(706, 567)
        self.centralwidget = QWidget(vtnPrincipal)
        self.centralwidget.setObjectName(u"centralwidget")
        self.btnNuevo = QPushButton(self.centralwidget)
        self.btnNuevo.setObjectName(u"btnNuevo")
        self.btnNuevo.setGeometry(QRect(160, 320, 75, 28))
        font = QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.btnNuevo.setFont(font)
        self.btnLimpiar = QPushButton(self.centralwidget)
        self.btnLimpiar.setObjectName(u"btnLimpiar")
        self.btnLimpiar.setGeometry(QRect(490, 320, 75, 28))
        self.btnLimpiar.setFont(font)
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(110, 150, 79, 130))
        self.splitter.setOrientation(Qt.Orientation.Vertical)
        self.lbNombre = QLabel(self.splitter)
        self.lbNombre.setObjectName(u"lbNombre")
        font1 = QFont()
        font1.setPointSize(14)
        font1.setBold(True)
        self.lbNombre.setFont(font1)
        self.splitter.addWidget(self.lbNombre)
        self.lbApellido = QLabel(self.splitter)
        self.lbApellido.setObjectName(u"lbApellido")
        self.lbApellido.setFont(font1)
        self.splitter.addWidget(self.lbApellido)
        self.lbCedula = QLabel(self.splitter)
        self.lbCedula.setObjectName(u"lbCedula")
        self.lbCedula.setFont(font1)
        self.splitter.addWidget(self.lbCedula)
        self.lbSexo = QLabel(self.splitter)
        self.lbSexo.setObjectName(u"lbSexo")
        self.lbSexo.setFont(font1)
        self.splitter.addWidget(self.lbSexo)
        self.lbEmail = QLabel(self.splitter)
        self.lbEmail.setObjectName(u"lbEmail")
        self.lbEmail.setFont(font1)
        self.splitter.addWidget(self.lbEmail)
        self.splitter_2 = QSplitter(self.centralwidget)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setGeometry(QRect(200, 151, 361, 132))
        self.splitter_2.setOrientation(Qt.Orientation.Vertical)
        self.txtNombre = QLineEdit(self.splitter_2)
        self.txtNombre.setObjectName(u"txtNombre")
        self.txtNombre.setMaxLength(50)
        self.splitter_2.addWidget(self.txtNombre)
        self.txtApellido = QLineEdit(self.splitter_2)
        self.txtApellido.setObjectName(u"txtApellido")
        self.txtApellido.setMaxLength(50)
        self.splitter_2.addWidget(self.txtApellido)
        self.txtCedula = QLineEdit(self.splitter_2)
        self.txtCedula.setObjectName(u"txtCedula")
        self.txtCedula.setMaxLength(10)
        self.splitter_2.addWidget(self.txtCedula)
        self.cbSexo = QComboBox(self.splitter_2)
        self.cbSexo.addItem("")
        self.cbSexo.addItem("")
        self.cbSexo.addItem("")
        self.cbSexo.setObjectName(u"cbSexo")
        self.splitter_2.addWidget(self.cbSexo)
        self.txtEmail = QLineEdit(self.splitter_2)
        self.txtEmail.setObjectName(u"txtEmail")
        self.txtEmail.setMaxLength(100)
        self.splitter_2.addWidget(self.txtEmail)
        self.btnBorrarRegistro = QPushButton(self.centralwidget)
        self.btnBorrarRegistro.setObjectName(u"btnBorrarRegistro")
        self.btnBorrarRegistro.setGeometry(QRect(350, 320, 121, 28))
        self.btnBorrarRegistro.setFont(font)
        self.btnActualizar = QPushButton(self.centralwidget)
        self.btnActualizar.setObjectName(u"btnActualizar")
        self.btnActualizar.setGeometry(QRect(250, 320, 78, 28))
        self.btnActualizar.setFont(font)
        self.splitter_3 = QSplitter(self.centralwidget)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setGeometry(QRect(110, 60, 358, 26))
        self.splitter_3.setOrientation(Qt.Orientation.Horizontal)
        self.lbBuscarCedula = QLabel(self.splitter_3)
        self.lbBuscarCedula.setObjectName(u"lbBuscarCedula")
        self.lbBuscarCedula.setFont(font1)
        self.splitter_3.addWidget(self.lbBuscarCedula)
        self.txtBuscarCedula = QLineEdit(self.splitter_3)
        self.txtBuscarCedula.setObjectName(u"txtBuscarCedula")
        self.txtBuscarCedula.setMaxLength(10)
        self.splitter_3.addWidget(self.txtBuscarCedula)
        self.btnBuscarCedula = QPushButton(self.splitter_3)
        self.btnBuscarCedula.setObjectName(u"btnBuscarCedula")
        self.btnBuscarCedula.setFont(font)
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditFind))
        self.btnBuscarCedula.setIcon(icon)
        self.splitter_3.addWidget(self.btnBuscarCedula)
        vtnPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(vtnPrincipal)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 706, 33))
        vtnPrincipal.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(vtnPrincipal)
        self.statusbar.setObjectName(u"statusbar")
        vtnPrincipal.setStatusBar(self.statusbar)

        self.retranslateUi(vtnPrincipal)

        QMetaObject.connectSlotsByName(vtnPrincipal)
    # setupUi

    def retranslateUi(self, vtnPrincipal):
        vtnPrincipal.setWindowTitle(QCoreApplication.translate("vtnPrincipal", u"Sistema de Gestion del Personal", None))
        self.btnNuevo.setText(QCoreApplication.translate("vtnPrincipal", u"Nuevo", None))
        self.btnLimpiar.setText(QCoreApplication.translate("vtnPrincipal", u"Limpiar", None))
        self.lbNombre.setText(QCoreApplication.translate("vtnPrincipal", u"Nombre:", None))
        self.lbApellido.setText(QCoreApplication.translate("vtnPrincipal", u"Apellido:", None))
        self.lbCedula.setText(QCoreApplication.translate("vtnPrincipal", u"C\u00e9dula:", None))
        self.lbSexo.setText(QCoreApplication.translate("vtnPrincipal", u"Sexo:", None))
        self.lbEmail.setText(QCoreApplication.translate("vtnPrincipal", u"E-mail", None))
        self.cbSexo.setItemText(0, QCoreApplication.translate("vtnPrincipal", u"Seleccionar", None))
        self.cbSexo.setItemText(1, QCoreApplication.translate("vtnPrincipal", u"Masculino", None))
        self.cbSexo.setItemText(2, QCoreApplication.translate("vtnPrincipal", u"Femenino", None))

        self.btnBorrarRegistro.setText(QCoreApplication.translate("vtnPrincipal", u"Borrar Registro", None))
        self.btnActualizar.setText(QCoreApplication.translate("vtnPrincipal", u"Actualizar", None))
        self.lbBuscarCedula.setText(QCoreApplication.translate("vtnPrincipal", u"Buscar por Cedula:", None))
        self.btnBuscarCedula.setText("")
    # retranslateUi

